baseURL = 'https://antybariera.pl/'
languageCode = 'pl-pl'
title = 'AntyBariera Dziennikarska Agaty Krokosz'
theme = 'antybariera_pl'

[pagination]
  disableAliases = false
  pagerSize = 20
  path = 'strona'