baseURL = 'https://antybariera.pl/'
languageCode = 'pl-pl'
DefaultContentLanguage = "pl"
title = 'AntyBariera Dziennikarska Agaty Krokosz'
theme = 'antybariera_pl'

[pagination]
  disableAliases = false
  pagerSize = 10
  path = 'strona'

[params]
  title_short = "AntyBariera"

  [params.author]
    name = 'Agata Krokosz'
    email = 'kontakt@antybariera.pl'